<p></p>
<div class="span12" style="margin-bottom: 15px; margin-top: 15px">
    <h3 style="float: left;"><i class="icon icon-pilot48"></i> <?php echo _NAME_; ?></h3>
</div>
<div class="span12">
    <ul class="breadcrumb">
        <i class="icon icon-color icon-arrowthick-ne"></i>
        <li>  
          <a href="#"><?php echo $this->getModule(); ?></a> <span class="divider">></span>  
        </li>
        <li>  
          <a href="#"><?php echo $this->getController(); ?></a> <span class="divider">></span>  
        </li>
        <li>  
          <a href="#" class="active"><?php echo $this->getAction(); ?></a></span>  
        </li>
    </ul>
</div>