
<div class="span12">
<ul>
    <li><a href="/demo/index/list">Exemplo listagem de Clientes</a></li>
    <li><a href="/demo/upload/upload">Exemplo inserção de Arquivos</a></li>
    <li><a href="/demo/index/grid">Exemplo de Grid</a></li>
</ul>
    
<button class="btn btn-primary noty" data-noty-options='{"text":"Teste de informação","layout":"topCenter","type":"success"}'><i class="icon-bell icon-white"></i> Top Full Width</button>
    
</div>

